name: Publish Dockerfile to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: railroad-team/switchboard

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle shadowJar
        run: ./gradlew shadowJar

      - name: List files
        run: ls -Rla

      - name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          mkdir temp
          cp $GITHUB_WORKSPACE/build/libs/Switchboard-all.jar temp/Switchboard.jar
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
          rm -rf temp

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
